// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"blog/internal/dao/internal"
)

// articleTagDao is the data access object for the table article_tag.
// You can define custom methods on it to extend its functionality as needed.
type articleTagDao struct {
	*internal.ArticleTagDao
}

var (
	// ArticleTag is a globally accessible object for table article_tag operations.
	ArticleTag = articleTagDao{internal.NewArticleTagDao()}
)

// Add your custom methods and functionality below.

