// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"blog/internal/dao/internal"
)

// categoryDao is the data access object for the table category.
// You can define custom methods on it to extend its functionality as needed.
type categoryDao struct {
	*internal.CategoryDao
}

var (
	// Category is a globally accessible object for table category operations.
	Category = categoryDao{internal.NewCategoryDao()}
)

// Add your custom methods and functionality below.
