// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"blog/internal/dao/internal"
)

// rolePermissionDao is the data access object for the table role_permission.
// You can define custom methods on it to extend its functionality as needed.
type rolePermissionDao struct {
	*internal.RolePermissionDao
}

var (
	// RolePermission is a globally accessible object for table role_permission operations.
	RolePermission = rolePermissionDao{internal.NewRolePermissionDao()}
)

// Add your custom methods and functionality below.
