// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"blog/internal/dao/internal"
)

// topicDao is the data access object for the table topic.
// You can define custom methods on it to extend its functionality as needed.
type topicDao struct {
	*internal.TopicDao
}

var (
	// Topic is a globally accessible object for table topic operations.
	Topic = topicDao{internal.NewTopicDao()}
)

// Add your custom methods and functionality below.
