// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"blog/internal/dao/internal"
)

// topicArticleDao is the data access object for the table topic_article.
// You can define custom methods on it to extend its functionality as needed.
type topicArticleDao struct {
	*internal.TopicArticleDao
}

var (
	// TopicArticle is a globally accessible object for table topic_article operations.
	TopicArticle = topicArticleDao{internal.NewTopicArticleDao()}
)

// Add your custom methods and functionality below.
