// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"blog/internal/dao/internal"
)

// visitLogDao is the data access object for the table visit_log.
// You can define custom methods on it to extend its functionality as needed.
type visitLogDao struct {
	*internal.VisitLogDao
}

var (
	// VisitLog is a globally accessible object for table visit_log operations.
	VisitLog = visitLogDao{internal.NewVisitLogDao()}
)

// Add your custom methods and functionality below.


